-- MySQL Script generated by MySQL Workbench
-- Fri Nov  4 10:49:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ExamenFactura
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ExamenFactura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ExamenFactura` DEFAULT CHARACTER SET utf8 ;
USE `ExamenFactura` ;

-- -----------------------------------------------------
-- Table `ExamenFactura`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExamenFactura`.`Tickets` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Cliente` VARCHAR(45) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `TipoSoporte` NVARCHAR(45) NOT NULL,
  `DescripcionSolicitada` NVARCHAR(50) NOT NULL,
  `DescripcionRespuesta` NVARCHAR(50) NOT NULL,
  `Precio` DECIMAL NOT NULL,
  `Impuesto` DECIMAL(8,2) NULL,
  `Descuento` DECIMAL(8,2) NULL,
  `Total` DECIMAL(8,2) NULL,
  `Usuario` NVARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
